version: '3'

services:
  scraper-cron:
    build: .
    container_name: scraper-cron
    environment:
       - TZ=Europe/Paris
       - maxLogSize=100000
       - xmx=600m
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    dns:
       - 8.8.8.8
    ports:
       - "8080:8080"
    restart: always
    networks:
      - monitoring

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - 'env.influxdb'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  grafana-storage:
  influxdb-storage: